# Generated by Django 6.0.5 on 2026-06-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_notification_enabled'),
        ('accounts', '0006_step4_cleanup_legacy_field'),
    ]

    operations = [
    ]
