# Generated by Django 6.0.5 on 2026-06-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260630_1038'),
        ('accounts', '0008_organization_updated_at_user_updated_at'),
    ]

    operations = [
    ]
